apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: html-app
  namespace: argocd
spec:
  destination:
    namespace: html-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/vedantsharmascaler/html-demo-app.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
